version: "3.8"

services:
  cbt_client:
    container_name: client
    build:
      context: ./client
      dockerfile: dockerfile.dev
    restart: on-failure
    depends_on:
      - api_server
    expose:
      80
    environment:
      - VIRTUAL_HOST: examtool.ml, www.examtool.ml
      - LETSENCRYPT_HOST: examtool.ml
      - LETSENCRYPT_EMAIL: jamiebones147@gmail.com

  api_server:
    container_name: app_server
    build:
      context: ./server
      dockerfile: dockerfile.prod
    volumes:
      - $HOME/uploads:/app/uploads
    depends_on:
      - mongodb_cbt
    restart: always
    ports:
      - 9000:9000
    environment:
      DB_HOST: mongodb_cbt ## same as the database service name
      DB_PORT: 27017
      DB_USER: jamiebones
      DB_DATABASE: CBT_Database
      DB_PASSWORD: blazing147

  mongodb_cbt:
    hostname: mongodb_cbt
    container_name: mongodb_cbt
    image: mongo
    ports:
      - 27900:27017
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: jamiebones
      MONGO_INITDB_ROOT_PASSWORD: blazing147
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--journal",
        "--dbpath",
        "/data/db",
        "--enableMajorityReadConcern",
        "false",
      ]
    volumes:
      - $HOME/cbt_data/mongodb_cbt:/data/db # This is where your volume will persist. e.g. VOLUME-DIR = ./volumes/mongodb
      - $HOME/cbt_data/mongodb_cbt_configdb:/data/configdb

  mongo-express_cbt:
    image: mongo-express
    container_name: mongo-express_cbt
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongodb_cbt
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb_cbt
      ME_CONFIG_MONGODB_ADMINUSERNAME: jamiebones
      ME_CONFIG_MONGODB_ADMINPASSWORD: blazing147
      ME_CONFIG_BASICAUTH_USERNAME: jamiebones
      ME_CONFIG_BASICAUTH_PASSWORD: blazing147
